# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-27 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zerovey', '0002_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
